In [1]:
import pandas as pd
import numpy as np

Importing the dataset

In [2]:
df = pd.read_csv("twcs.csv")

In [3]:
df.head()

tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017   
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017   
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017   
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017   
4         5      115712     True  Tue Oct 31 21:49:35 +0000 2017   

                                                text response_tweet_id  \
0  @115712 I understand. I would like to assist y...                 2   
1      @sprintcare and how do you propose we do that               NaN   
2  @sprintcare I have sent several private messag...                 1   
3  @115712 Please send us a Private Message so th...                 3   
4                                 @sprintcare I did.                 4   

   in_response_to_tweet_id  
0                      3.0  
1                      1.0  
2                      4.0  
3                      5.0  
4                      6.0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
BOW=CountVectorizer()

In [6]:
document_matrix=BOW.fit_transform(df["text"])

In [7]:
document_matrix

<30468x36163 sparse matrix of type '<class 'numpy.int64'>'
	with 500885 stored elements in Compressed Sparse Row format>

In [8]:
BOW.vocabulary_

{'115712': 410,
 'understand': 32641,
 'would': 34182,
 'like': 23186,
 'to': 31897,
 'assist': 12731,
 'you': 34702,
 'we': 33716,
 'need': 25006,
 'get': 19594,
 'into': 21621,
 'private': 27228,
 'secured': 29523,
 'link': 23227,
 'further': 19303,
 'sprintcare': 30557,
 'and': 12259,
 'how': 20799,
 'do': 17154,
 'propose': 27348,
 'that': 31594,
 'have': 20346,
 'sent': 29616,
 'several': 29697,
 'messages': 24212,
 'no': 25234,
 'one': 25772,
 'is': 21748,
 'responding': 28578,
 'as': 12646,
 'usual': 32900,
 'please': 26782,
 'send': 29597,
 'us': 32872,
 'message': 24210,
 'so': 30247,
 'can': 14431,
 'just': 22252,
 'click': 15081,
 'at': 12764,
 'the': 31600,
 'top': 31967,
 'of': 25624,
 'your': 34710,
 'profile': 27293,
 'did': 16792,
 'gain': 19385,
 'details': 16676,
 'about': 11415,
 'account': 11494,
 'worst': 34170,
 'customer': 16061,
 'service': 29662,
 '115713': 411,
 'this': 31663,
 'saddening': 29177,
 'hear': 20418,
 'shoot': 29846,
 'dm': 17130,
 'look': 23431,


In [9]:
document_matrix[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [10]:
bigram=CountVectorizer(ngram_range=(2,2))

In [11]:
bigramvocab=bigram.fit_transform(df["text"])

In [12]:
bigram.vocabulary_

{'115712 understand': 968,
 'understand would': 178137,
 'would like': 190693,
 'like to': 107172,
 'to assist': 172076,
 'assist you': 37227,
 'you we': 193761,
 'we would': 185201,
 'would need': 190701,
 'need to': 118786,
 'to get': 172629,
 'get you': 83305,
 'you into': 192963,
 'into private': 98235,
 'private secured': 137758,
 'secured link': 149482,
 'link to': 107549,
 'to further': 172616,
 'further assist': 82041,
 'sprintcare and': 157032,
 'and how': 31166,
 'how do': 93327,
 'do you': 68676,
 'you propose': 193330,
 'propose we': 138698,
 'we do': 184922,
 'do that': 68622,
 'sprintcare have': 157057,
 'have sent': 88827,
 'sent several': 150431,
 'several private': 151427,
 'private messages': 137754,
 'messages and': 113469,
 'and no': 31397,
 'no one': 120536,
 'one is': 127078,
 'is responding': 99710,
 'responding as': 144866,
 'as usual': 36134,
 '115712 please': 967,
 'please send': 135459,
 'send us': 150257,
 'us private': 180179,
 'private message': 137753,
 '

In [13]:
trigram=CountVectorizer(ngram_range=(3,3))

In [14]:
trigramdata=trigram.fit_transform(df["text"])

In [15]:
trigram.vocabulary_

{'115712 understand would': 1223,
 'understand would like': 289450,
 'would like to': 314051,
 'like to assist': 165662,
 'to assist you': 275841,
 'assist you we': 51675,
 'you we would': 321499,
 'we would need': 302840,
 'would need to': 314073,
 'need to get': 185132,
 'to get you': 278031,
 'get you into': 117976,
 'you into private': 318804,
 'into private secured': 148501,
 'private secured link': 217125,
 'secured link to': 232902,
 'link to further': 166384,
 'to further assist': 277843,
 'sprintcare and how': 244701,
 'and how do': 39848,
 'how do you': 135620,
 'do you propose': 94693,
 'you propose we': 319832,
 'propose we do': 218315,
 'we do that': 301467,
 'sprintcare have sent': 244737,
 'have sent several': 127492,
 'sent several private': 234647,
 'several private messages': 236365,
 'private messages and': 217120,
 'messages and no': 175839,
 'and no one': 40590,
 'no one is': 187952,
 'one is responding': 201114,
 'is responding as': 151868,
 'responding as usual':

In [16]:
mix=CountVectorizer(ngram_range=(1,2))

In [17]:
mix_vocab=mix.fit_transform(df["text"])

In [18]:
mix.vocabulary_

{'115712': 1374,
 'understand': 210713,
 'would': 224809,
 'like': 130125,
 'to': 203735,
 'assist': 49864,
 'you': 227076,
 'we': 218541,
 'need': 143649,
 'get': 102512,
 'into': 119758,
 'private': 164973,
 'secured': 179004,
 'link': 130676,
 'further': 101330,
 '115712 understand': 1379,
 'understand would': 210779,
 'would like': 224876,
 'like to': 130359,
 'to assist': 203974,
 'assist you': 49959,
 'you we': 228464,
 'we would': 218918,
 'would need': 224884,
 'need to': 143793,
 'to get': 204527,
 'get you': 102900,
 'you into': 227666,
 'into private': 119857,
 'private secured': 164987,
 'secured link': 179006,
 'link to': 130777,
 'to further': 204514,
 'further assist': 101345,
 'sprintcare': 187573,
 'and': 42703,
 'how': 114090,
 'do': 85484,
 'propose': 166045,
 'that': 195020,
 'sprintcare and': 187590,
 'and how': 43426,
 'how do': 114127,
 'do you': 85831,
 'you propose': 228033,
 'propose we': 166047,
 'we do': 218639,
 'do that': 85777,
 'have': 108561,
 'sent': 1

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
tfidf=TfidfVectorizer()

In [21]:
tfidf.fit_transform(df["text"]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
tfidf.get_feature_names_out()

array(['00', '000', '0001', ..., 'ｿｰｯｯ', 'ﾉωﾉ', 'ﾉﾌﾟﾝﾌﾟﾝ'], dtype=object)

In [23]:
tfidf.idf_

array([ 7.11977243,  8.49125171, 10.63131787, ..., 10.22585276,
       10.63131787, 10.63131787])